### ISSUE TITLE
Cannot remove broken eea.progressbar

### ISSUE THREAD

**Issue by maruberto** [eea/eea.progressbar#2]
I migrated my Plone site but didn't pin the versions for addons. I now have a broken addon that I cannot update or uninstall. In the addons control panel I have this message.
"This add-on has been upgraded. Old profile version was 2.2. New profile version is 3.0. Upgrade:"
And all pages contain this error:
error while rendering eea.progressbar error while rendering eea.progresstrail error while rendering eea.progressmetadata

Clicking the deactivate link gives the following error:
2015-04-21T16:28:08 ERROR Zope.SiteErrorLog 1429648088.150.677553329487 http://cardadmin/portal_quickinstaller/uninstallProducts
Traceback (innermost last):
  Module ZPublisher.Publish, line 146, in publish
  Module Zope2.App.startup, line 301, in commit
  Module transaction._manager, line 89, in commit
  Module transaction._transaction, line 329, in commit
  Module transaction._transaction, line 443, in _commitResources
  Module ZODB.Connection, line 567, in commit
  Module ZODB.Connection, line 623, in _commit
  Module ZODB.Connection, line 658, in _store_objects
  Module ZODB.serialize, line 422, in serialize
  Module ZODB.serialize, line 431, in _dump
PicklingError: Can't pickle <class 'eea.annotator.browser.interfaces.ILayer'>: import of module eea.annotator.browser.interfaces$

How do I get rid of this? I tried removing it from buildout and re-run buildout. No help.
My installation info is:

```
Plone 4.3.2 (4307)

CMF 2.2.7

Zope 2.13.21

Python 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

PIL 1.7.8 (Pillow)
```

**Comment by avoinea** [comment]
Did you try to re-install eea.progressbar (within portal_quickinstaller/manage_installProductsForm)

If the reinstall works, and still want to uninstall eea.progressbar:
- Go to Site Setup > Add-ons and uninstall EEA Progress Bar
- Go to ZMI and remove portal_progress
- Remove eea.progressbar from your buildout
- Re-run buildout and restart Zope

Still don't know what's the relation with eea.annotator. Did you have eea.annotator installed at some point and then removed it from your buildout?

**Comment by maruberto** [comment]
annotator was installed on the former instance of Plone before migration but was cleanly uninstalled - or so I thought.
But now, as per your advice I have tried reinstalling progressbar and that results in the following error.
Traceback (innermost last):

```
Module ZPublisher.Publish, line 146, in publish
Module Zope2.App.startup, line 301, in commit
Module transaction._manager, line 89, in commit
Module transaction._transaction, line 329, in commit
Module transaction._transaction, line 443, in _commitResources
Module ZODB.Connection, line 567, in commit
Module ZODB.Connection, line 623, in _commit
Module ZODB.Connection, line 658, in _store_objects
Module ZODB.serialize, line 422, in serialize
Module ZODB.serialize, line 431, in _dump
```

PicklingError: Can't pickle <class 'eea.annotator.browser.interfaces.ILayer'>: import of module eea.annotator.browser.interfaces failed 

Yet in this new Plone instance annotator was never installed and there is no trace of it's code to be found anywhere. Despite it being uninstalled in the former Plone instance something of it carried over through the ZODB and is now poisoning progressbar.

**Comment by avoinea** [comment]
You're issue has nothing to do with eea.progressbar. It's related to eea.annotator only, thus:
- Re-add eea.annotator within buildout eggs and zcml section and re-run buildout
- Restart zope
- Look for any **Inline comments** portlet within your site and remove it (you may need to re-install eea.annotator from Site Setup > Add-ons)
- Uninstall eea.annotator and remove it from buildout
